version: '3.9'

services:
  database:
    image: mongo
    container_name: database
    ports:
      - "5434:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PWD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    volumes:
      - ./server:/app
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client
    volumes:
      - ./client:/app
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - server
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - client
      - server
    networks:
      - app-network

volumes:
  mongoDB_data:

networks:
  app-network:
    driver: bridge
