version: '3.9'
services:
  backend:
    container_name: server
    build: ./server
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FE_CONTAINER_HOST: ${FE_CONTAINER_HOST}
      FRONTEND_HOST: ${FRONTEND_HOST}
      JWT_SECRET: ${JWT_SECRET}
      JWT_SESSION: ${JWT_SESSION}
      GOOGLE_APP_UID: ${GOOGLE_APP_UID}
      GOOGLE_APP_SECRET: ${GOOGLE_APP_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
    networks:
      - network

  frontend:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_BACKEND_HOST: ${BACKEND_HOST}
      NEXT_PUBLIC_BE_CONTAINER_HOST: ${BE_CONTAINER_HOST}
    depends_on:
      - backend
    networks:
      - network
networks:
  network: