import type { Metadata } from "next";
import React from "react";
import "./style/globals.css";
import ClientOnlyNavBar from "../components/navbar/ClientOnNavBar"; 

export const metadata: Metadata = {
  title: "ClassHive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className="h-screen" >
        <header className="h-[12%]">
            <ClientOnlyNavBar />
        </header>
        <main className="h-[88%]">
          {children}
        </main>
        </body>
    </html>
  );
}
