import { Metadata } from "next";
import React from "react";
import { GoogleOAuthProvider } from "@react-oauth/google";
import "./style/globals.css";
import ClientOnlyNavBar from "../components/navbar/ClientOnNavBar"; 

export const metadata: Metadata = {
  title: "ClassHive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const clientId = "";

  return (
    <html lang="en">
      <body className="h-screen w-screen">
        <GoogleOAuthProvider clientId={clientId}>
          <header className="h-[13%]">
            <ClientOnlyNavBar />
          </header>
          <main className="flex w-full h-[85%]">
            {children}
          </main>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
